const PAGE_SIZE=24;
if(!document.querySelector('#sourceStatus')){const node=document.createElement('p');node.id='sourceStatus';node.className='source-status';node.setAttribute('aria-live','polite');document.querySelector('.hero .wrap')?.append(node)}
const esc=value=>(value||'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const fmt=value=>value?new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Taipei'}).format(new Date(value)):'時間未提供';
const articleHasBody=article=>(article.summary||'').trim().length>0;
const articleTarget=article=>articleHasBody(article)&&article.url?article.url:(article.siteUrl||article.sourceUrl||article.url);
const articleLabel=article=>articleHasBody(article)?'閱讀公告':'此篇只有附檔 請前往官網查看';
const articleSummary=article=>(article.summary||'').trim()||((article.attachments||[]).length?'':'附件名稱未由來源提供，請前往官網查看。');
const articleAttachments=article=>(article.attachments||[]).filter(Boolean).map(item=>{const name=typeof item==='string'?item:item.name;return item.url?`<a class="attachment" href="${esc(item.url)}" target="_blank" rel="noopener">附件：${esc(name)}</a>`:`<span class="attachment">附件：${esc(name)}</span>`}).join('');
const taiwanDate=value=>value?new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value)):'';

const mergeArticles=articles=>{const merged=new Map();articles.forEach(article=>{const schools=article.schools||['仁愛國小'];const normalizedTitle=(article.title||'').replace(/^(轉知[:：]\s*)+/,'');const key=normalizedTitle+'::'+schools.slice().sort().join('|');const current=merged.get(key);if(!current){merged.set(key,{...article,schools:[...schools],sources:[...(article.sources||[article.source]).filter(Boolean)]});return}current.schools=[...new Set([...current.schools,...schools])];current.sources=[...new Set([...current.sources,...(article.sources||[article.source]).filter(Boolean)])];if((article.summary||'').length>(current.summary||'').length)current.summary=article.summary;if(article.published>current.published)current.published=article.published;if((article.attachments||[]).length>(current.attachments||[]).length)current.attachments=article.attachments});return [...merged.values()]};

const rootPath=schoolMeta=>location.pathname.replace(new RegExp('('+Object.values(schoolMeta).map(meta=>meta.slug).join('|')+')\\/?$'),'');
const loadData=async()=>{const versionResponse=await fetch('data/version.json?refresh='+Date.now(),{cache:'no-store'});if(!versionResponse.ok)throw new Error('版本資料無法載入');const version=await versionResponse.json();const configResponse=await fetch('config.json?refresh='+Date.now(),{cache:'no-store'});const dataResponse=await fetch('data/articles.json?v='+encodeURIComponent(version.updatedAt||''));if(!configResponse.ok||!dataResponse.ok)throw new Error('設定或文章資料無法載入');return {config:await configResponse.json(),data:await dataResponse.json()}};

loadData().then(({config,data})=>{const schoolMeta=config.schoolMeta||{};const schools=config.schools||Object.keys(schoolMeta);const activeSchool=schools.find(s=>new RegExp('/'+schoolMeta[s]?.slug+'(?:/|$)').test(location.pathname))||schools[0];const articles=mergeArticles(data.articles||[]);const updated=document.querySelector('#updated');const status=document.querySelector('#sourceStatus');const switcher=document.querySelector('#schoolSwitch');const title=document.querySelector('#schoolTitle');const filters=document.querySelector('#filters');const feed=document.querySelector('#feed');const pagination=document.querySelector('#pagination');const search=document.querySelector('#search');const today=taiwanDate(new Date());const visibleForSchool=articles.filter(article=>(article.schools||['仁愛國小']).includes(activeSchool));const todayCount=visibleForSchool.filter(article=>taiwanDate(article.published)===today).length;updated.textContent=data.updatedAt?'資料更新｜'+fmt(data.updatedAt)+'｜今日新增 '+todayCount+' 筆':'尚未更新';if(status){const errors=(data.sourceStatus||[]).filter(item=>item.status==='error');status.textContent=errors.length?'部分來源暫時無法更新：'+errors.map(item=>item.name).join('、'):'所有來源更新正常';status.classList.toggle('warning',errors.length>0)}let active='全部';let page=1;let query='';
  switcher.innerHTML=schools.map(s=>`<button type="button" class="school-tab ${s===activeSchool?'active':''}" aria-pressed="${s===activeSchool}" data-school="${esc(s)}">${esc(s)}</button>`).join('');
  switcher.querySelectorAll('.school-tab').forEach(button=>button.onclick=()=>{location.href=rootPath(schoolMeta)+schoolMeta[button.dataset.school].slug+'/'});
  title.innerHTML=esc(activeSchool)+'<br><em>消息牆</em><a class="official-site" href="'+esc(schoolMeta[activeSchool].site)+'" target="_blank" rel="noopener">官方網站</a>';
  const visible=visibleForSchool;
  const groups=[...new Set(visible.flatMap(article=>article.sources||[article.source]).filter(Boolean))];
  filters.innerHTML=['全部',...groups].map(group=>`<button type="button" class="filter ${group===active?'active':''}" data-source="${esc(group)}">${esc(group)}</button>`).join('');
  const matches=article=>{const text=[article.title,article.summary,article.source,...(article.sources||[]),...(article.attachments||[]).map(item=>typeof item==='string'?item:item.name)].filter(Boolean).join(' ').toLocaleLowerCase('zh-TW');return !query||text.includes(query.toLocaleLowerCase('zh-TW'))};
  const paint=()=>{const list=visible.filter(article=>(active==='全部'||(article.sources||[article.source]).includes(active))&&matches(article));const totalPages=Math.max(1,Math.ceil(list.length/PAGE_SIZE));page=Math.min(page,totalPages);const pageItems=list.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);feed.innerHTML=pageItems.length?pageItems.map(article=>`<article class="card"><div class="meta"><span class="badges">${(article.sources||[article.source]).map(source=>`<span class="tag">${esc(source)}</span>`).join('')}</span><time>${esc(fmt(article.published))}</time></div><h2>${esc(article.title)}</h2>${articleTarget(article)?`<a class="read" href="${esc(articleTarget(article))}" target="_blank" rel="noopener">${articleLabel(article)} <span>↗</span></a>`:`<p class="summary">${esc(articleSummary(article))}</p>`}${articleAttachments(article)}</article>`).join(''):'<p class="empty">目前沒有符合條件的消息。</p>';const start=Math.min(Math.max(1,page-2),Math.max(1,totalPages-4));const end=Math.min(totalPages,start+4);pagination.innerHTML=`<span class="pagination-total">共 ${totalPages} 頁 ${list.length} 筆</span><button type="button" class="page-nav" data-page="${page-1}" ${page===1?'disabled':''}>上一頁</button>${Array.from({length:end-start+1},(_,index)=>start+index).map(number=>`<button type="button" class="page-number ${number===page?'active':''}" data-page="${number}" aria-current="${number===page?'page':'false'}">${number}</button>`).join('')}<button type="button" class="page-nav" data-page="${page+1}" ${page===totalPages?'disabled':''}>下一頁</button>`;pagination.querySelectorAll('button:not([disabled])').forEach(button=>button.onclick=()=>{page=Number(button.dataset.page);paint();feed.scrollIntoView({behavior:'smooth',block:'start'})})};
  filters.querySelectorAll('.filter').forEach(button=>button.onclick=()=>{active=button.dataset.source;page=1;paint()});
  if(search)search.oninput=()=>{query=search.value.trim();page=1;paint()};
  paint();
}).catch(error=>{console.error(error);document.querySelector('#feed').innerHTML='<p class="empty">暫時無法載入消息資料，請稍後再試。</p>'});
